spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project1
    username: root
    password: FB20020910

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-aliases-package: com.neu.dao.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8085
